apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 10.10.30.17
      user: root
      port: 22
      keyPath: /root/.ssh/id_rsa_k0s
    role: controller
    privateInterface: eth0
  - ssh:
      address: 10.10.30.18
      user: root
      port: 22
      keyPath: /root/.ssh/id_rsa_k0s
    role: controller
    privateInterface: eth0
  - ssh:
      address: 10.10.30.21
      user: root
      port: 22
      keyPath: /root/.ssh/id_rsa_k0s
    role: controller
    privateInterface: eth0
  - ssh:
      address: 10.10.30.22
      user: root
      port: 22
      keyPath: /root/.ssh/id_rsa_k0s
    role: worker
    privateInterface: eth0
  k0s:
    config:
      spec:
        api:
          externalAddress: 10.10.30.23
          sans:
          - 10.10.30.23
    version: 1.22.3+k0s.0
