apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 10.10.33.6
      user: root
      port: 22
      keyPath: /root/.ssh/id_rsa_k0s
    role: controller
    privateInterface: eth0
  - ssh:
      address: 10.10.33.7
      user: root
      port: 22
      keyPath: /root/.ssh/id_rsa_k0s
    role: controller
    privateInterface: eth0
  - ssh:
      address: 10.10.33.8
      user: root
      port: 22
      keyPath: /root/.ssh/id_rsa_k0s
    role: controller
    privateInterface: eth0
  - ssh:
      address: 10.10.33.9
      user: root
      port: 22
      keyPath: /root/.ssh/id_rsa_k0s
    role: worker
    privateInterface: eth0
  k0s:
    config:
      spec:
        api:
          externalAddress: 10.10.33.10
          sans:
          - 10.10.33.10
    version: 1.22.2+k0s.1
